config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root  'home_pages#index'

    get   :cart,     to: "orders#edit"
    patch :cart,     to: "orders#update"
    post  :populate, to: "orders#populate"

    patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout
    get   "/checkout/:state",        to: "checkout#edit",   as: :checkout_state
    get   "/checkout",               to: "checkout#edit"

    resources :orders,              only: [:show, :edit, :update]
    resources :line_items,          only: [:destroy]
    resources :home_pages,          only: [:index]
    resources :categories,          only: [:show]
    resources :products,            only: [:show] do
      collection do
        get :search
      end
    end

    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.includes(:taxons)
    @taxon = Spree::Taxon.find(params[:id])
    @color_values = Spree::OptionType.find_by(presentation: "Color").option_values
    @size_values = Spree::OptionType.find_by(presentation: "Size").option_values
    @products = @taxon.all_products.includes(master: [:default_price, :images]).order(available_on: :desc)

    if params[:value] && params[:sort]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_value(params[:value]).
        sort_out_by(params[:sort])
    elsif params[:value]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_value(params[:value]).order(available_on: :desc)
    elsif params[:sort]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        sort_out_by(params[:sort])
    end
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  before_action :load_order
  before_action :set_state_if_present

  before_action :ensure_order_not_completed
  before_action :ensure_checkout_allowed
  before_action :ensure_sufficient_stock_lines
  before_action :ensure_valid_state

  before_action :associate_user
  before_action :check_authorization

  before_action :setup_for_current_state, only: [:edit, :update]

  rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end
      if @order.completed?
        finalize_order
      else
        send_to_next_state
      end
    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
  end

  def send_to_next_state
    @order.next if @order.state == "delivery"
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def update_params
    update_params = massaged_params[:order]
    if update_params.present?
      update_params.permit(permitted_checkout_attributes)
    else
      # パラメータなしの更新リクエストを許可
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    if massaged_params[:order] && massaged_params[:order][:existing_card].present?
      move_existing_card_into_payments_attributes(massaged_params)
    end
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  # solidusのチェックアウトステップ内のステップに
  # 一致しないチェックアウトの領域がある場合は、オーバーライドする必要がある
  def skip_state_validation?
    false
  end

  # @orderがない場合、カートページに遷移
  def load_order
    @order = current_order
    redirect_to(potepan_cart_path) && return unless @order
  end

  # params[:state]がある場合、次のステップへ進む
  def set_state_if_present
    if params[:state]
      if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
        redirect_to potepan_checkout_state_path(@order.state)
      end
      @order.state = params[:state]
    end
  end

  # order内に、アイテムがあることを確認
  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to potepan_cart_path
    end
  end

  def ensure_order_not_completed
    redirect_to potepan_cart_path if @order.completed?
  end

  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_lines.present?
      out_of_stock_items = @order.insufficient_stock_lines.collect(&:name).to_sentence
      flash[:error] =
        t('spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items)
      redirect_to potepan_cart_path
    end
  end

  def ensure_valid_state
    unless skip_state_validation?
      if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
        (!params[:state] && !@order.has_checkout_step?(@order.state))
        @order.state = 'cart'
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
      end
    end
  end

  def completion_route
    potepan_order_path(@order.number)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    default = { country_id: Spree::Country.default.id }
    @order.build_ship_address(default) unless @order.ship_address
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = try_spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                      @wallet_payment_sources.first

      @payment_sources = deprecated_payment_sources
    end
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
    @order.errors.add(:base, exception.message)
    render :edit
  end

  def check_authorization
    authorize!(:edit, current_order, cookies.signed[:guest_token])
  end

  def insufficient_stock_error
    packages = @order.shipments.map(&:to_package)
    if packages.empty?
      flash[:error] = I18n.t('spree.insufficient_stock_for_order')
      redirect_to potepan_cart_path
    else
      availability_validator = Spree::Stock::AvailabilityValidator.new
      unavailable_items = @order.line_items.reject { |line_item| availability_validator.validate(line_item) }
      if unavailable_items.any?
        item_names = unavailable_items.map(&:name).to_sentence
        flash[:error] =
          t('spree.inventory_error_flash_for_insufficient_shipment_quantity',
            unavailable_items: item_names)
        @order.restart_checkout_flow
        redirect_to potepan_checkout_state_path(@order.state)
      end
    end
  end

  def deprecated_payment_sources
    try_spree_current_user.wallet.user.wallet_payment_sources.includes(:payment_source).
      map(&:payment_source).
      select { |ps| ps.is_a?(Spree::CreditCard) }
  end
end

app/controllers/potepan/home_pages_controller.rb
class Potepan::HomePagesController < ApplicationController
  NEW_PRODUCT_MAX_NUM = 8

  def index
    @new_release_products = Spree::Product.desc_order_available.limit(NEW_PRODUCT_MAX_NUM)
    @categories = Spree::Taxon.where(name: %w(bags t-shirts mugs))
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  def destroy
    line_item = Spree::LineItem.find_by(id: params[:id])
    line_item.order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  before_action :assign_order, only: :update

  def show
    @order = Spree::Order.find_by(number: params[:id])
    authorize! :read, @order, cookies.signed[:guest_token]
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    unless quantity.between?(1, 100)
      @order.errors.add(:base, t('spree.please_enter_reasenable_quantity'))
    end

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default(potepan_root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def edit
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    @line_items = @order.line_items.includes(variant: [:images, :product])
    authorize! :read, @order, cookies.signed[:guest_token]
    associate_user
  end

  def update
    authorize! :update, @order, cookies.signed[:guest_token]
    if @order.contents.update_cart(update_order_params)
      if params.key?(:checkout)
        @order.next if @order.cart?
        redirect_to potepan_checkout_state_path(@order.state)
        return
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def update_order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = "注文が見つかりませんでした"
      redirect_to potepan_root_path
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCT_MAX_NUM = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products(RELATED_PRODUCT_MAX_NUM)
  end

  def search
    if params[:search]
      @search_keyword = params[:search]
      @search_products = Spree::Product.in_name_or_description(@search_keyword)
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/views/potepan/orders/_line_item.html.erb
<%= f.fields_for :line_items, line_item do |item_form| %>
  <% variant = line_item.variant %>
  <%= item_form.hidden_field :id, value: line_item.id %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item.id), method: :delete, id: "delete_button" do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% end %>
      <span class="cartImage">
        <%= image_tag(variant.display_image.url(:small)) %>
    </td>
    <td class="col-xs-4"><%= link_to line_item.name, potepan_product_path(variant.product.id) %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= item_form.number_field :quantity, min: 0, max: 100 %></td>
    <td class="col-xs-2 line-item-amount"><%= line_item.display_amount unless line_item.quantity.nil? %></td>
  </tr>
<% end %>

app/views/potepan/orders/_order_form.html.erb
<%= form_with model: @order, url: potepan_cart_path, local: true do |f| %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>商品名</th>
          <th>価格</th>
          <th>数</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "line_item", collection: line_items, locals: { f: f } %>
      </tbody>
    </table>
  </div>
  <div class="updateArea">
    <%= f.submit "アップデート", class: "btn" %>
  </div>
    <%= render 'total_amount', order: order %>
  <div class="checkBtnArea">
    <%= f.button class: "btn btn-primary btn-block", name: "checkout" do %>
      購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/orders/_total_amount.html.erb
<div class="totalAmountArea">
  <div class="col-sm-4 col-sm-offset-8 col-xs-12">
    <ul class="list-unstyled">
      <li>小計 <span><%= order.display_item_total %></span></li>
      <li>消費税 <span><%= order.display_tax_total %></span></li>
      <li>総計 <span class="grandTotal"><%= order.display_total %></span></li>
    </ul>
  </div>
</div>

app/views/potepan/orders/edit.html.erb
<% provide :title, "Cart" %>
<%= render 'shared/light_section', page_title: "Cart" %>
<div class="main-wrapper">
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix cartListWrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="cartListInner">
            <% if @line_items.blank? %>
              カートは空です。
            <% else %>
              <%= render partial: "order_form", locals: { order: @order, line_items: @line_items } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/potepan/orders/show.html.erb
<% provide :title, "Order Complete" %>
<%= render 'shared/light_section', page_title: "Thanks message" %>
<div class="main-wrapper">
  <section class= "mainContent clearfix setp5">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="thanksContent">
            <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
            <h3>Shipping Details</h3>
            <div class="thanksInner">
              <div class="row">
                <div class="col-sm-6 col-xs-12 tableBlcok">
                  <%= render 'shared/confirm_address', order: @order, address: @order.ship_address %>
                </div>
                <div class="col-sm-6 col-xs-12">
                  <div class="well">
                    <h2><small>Order ID</small><%= @order.number %></h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>