config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root  'home_pages#index'

    get   :cart,     to: "orders#edit"
    patch :cart,     to: "orders#update"
    post  :populate, to: "orders#populate"

    patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout
    get   "/checkout/:state",        to: "checkout#edit",   as: :checkout_state
    get   "/checkout",               to: "checkout#edit"

    resources :orders,              only: [:show, :edit, :update]
    resources :line_items,          only: [:destroy]
    resources :home_pages,          only: [:index]
    resources :categories,          only: [:show]
    resources :products,            only: [:show] do
      collection do
        get :search
      end
    end

    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.includes(:taxons)
    @taxon = Spree::Taxon.find(params[:id])
    @color_values = Spree::OptionType.find_by(presentation: "Color").option_values
    @size_values = Spree::OptionType.find_by(presentation: "Size").option_values
    @products = @taxon.all_products.includes(master: [:default_price, :images]).order(available_on: :desc)

    if params[:value] && params[:sort]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_value(params[:value]).
        sort_out_by(params[:sort])
    elsif params[:value]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_value(params[:value]).order(available_on: :desc)
    elsif params[:sort]
      @products = @taxon.all_products.includes(master: [:default_price, :images]).
        sort_out_by(params[:sort])
    end
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  before_action :load_order
  before_action :set_state_if_present

  before_action :ensure_order_not_completed
  before_action :ensure_checkout_allowed
  before_action :ensure_sufficient_stock_lines
  before_action :ensure_valid_state

  before_action :associate_user
  before_action :check_authorization

  before_action :setup_for_current_state, only: [:edit, :update]

  rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end
      if @order.completed?
        finalize_order
      else
        send_to_next_state
      end
    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
  end

  def send_to_next_state
    @order.next if @order.state == "delivery"
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def update_params
    update_params = massaged_params[:order]
    if update_params.present?
      update_params.permit(permitted_checkout_attributes)
    else
      # パラメータなしの更新リクエストを許可
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    if massaged_params[:order] && massaged_params[:order][:existing_card].present?
      move_existing_card_into_payments_attributes(massaged_params)
    end
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  # solidusのチェックアウトステップ内のステップに
  # 一致しないチェックアウトの領域がある場合は、オーバーライドする必要がある
  def skip_state_validation?
    false
  end

  # @orderがない場合、カートページに遷移
  def load_order
    @order = current_order
    redirect_to(potepan_cart_path) && return unless @order
  end

  # params[:state]がある場合、次のステップへ進む
  def set_state_if_present
    if params[:state]
      if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
        redirect_to potepan_checkout_state_path(@order.state)
      end
      @order.state = params[:state]
    end
  end

  # order内に、アイテムがあることを確認
  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to potepan_cart_path
    end
  end

  def ensure_order_not_completed
    redirect_to potepan_cart_path if @order.completed?
  end

  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_lines.present?
      out_of_stock_items = @order.insufficient_stock_lines.collect(&:name).to_sentence
      flash[:error] =
        t('spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items)
      redirect_to potepan_cart_path
    end
  end

  def ensure_valid_state
    unless skip_state_validation?
      if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
        (!params[:state] && !@order.has_checkout_step?(@order.state))
        @order.state = 'cart'
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
      end
    end
  end

  def completion_route
    potepan_order_path(@order.number)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    default = { country_id: Spree::Country.default.id }
    @order.build_ship_address(default) unless @order.ship_address
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = try_spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                      @wallet_payment_sources.first

      @payment_sources = deprecated_payment_sources
    end
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
    @order.errors.add(:base, exception.message)
    render :edit
  end

  def check_authorization
    authorize!(:edit, current_order, cookies.signed[:guest_token])
  end

  def insufficient_stock_error
    packages = @order.shipments.map(&:to_package)
    if packages.empty?
      flash[:error] = I18n.t('spree.insufficient_stock_for_order')
      redirect_to potepan_cart_path
    else
      availability_validator = Spree::Stock::AvailabilityValidator.new
      unavailable_items = @order.line_items.reject { |line_item| availability_validator.validate(line_item) }
      if unavailable_items.any?
        item_names = unavailable_items.map(&:name).to_sentence
        flash[:error] =
          t('spree.inventory_error_flash_for_insufficient_shipment_quantity',
            unavailable_items: item_names)
        @order.restart_checkout_flow
        redirect_to potepan_checkout_state_path(@order.state)
      end
    end
  end

  def deprecated_payment_sources
    try_spree_current_user.wallet.user.wallet_payment_sources.includes(:payment_source).
      map(&:payment_source).
      select { |ps| ps.is_a?(Spree::CreditCard) }
  end
end

app/controllers/potepan/home_pages_controller.rb
class Potepan::HomePagesController < ApplicationController
  NEW_PRODUCT_MAX_NUM = 8

  def index
    @new_release_products = Spree::Product.desc_order_available.limit(NEW_PRODUCT_MAX_NUM)
    @categories = Spree::Taxon.where(name: %w(bags t-shirts mugs))
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  def destroy
    line_item = Spree::LineItem.find_by(id: params[:id])
    line_item.order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  before_action :assign_order, only: :update

  def show
    @order = Spree::Order.find_by(number: params[:id])
    authorize! :read, @order, cookies.signed[:guest_token]
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    unless quantity.between?(1, 100)
      @order.errors.add(:base, t('spree.please_enter_reasenable_quantity'))
    end

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default(potepan_root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def edit
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    @line_items = @order.line_items.includes(variant: [:images, :product])
    authorize! :read, @order, cookies.signed[:guest_token]
    associate_user
  end

  def update
    authorize! :update, @order, cookies.signed[:guest_token]
    if @order.contents.update_cart(update_order_params)
      if params.key?(:checkout)
        @order.next if @order.cart?
        redirect_to potepan_checkout_state_path(@order.state)
        return
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def update_order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = "注文が見つかりませんでした"
      redirect_to potepan_root_path
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCT_MAX_NUM = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products(RELATED_PRODUCT_MAX_NUM)
  end

  def search
    if params[:search]
      @search_keyword = params[:search]
      @search_products = Spree::Product.in_name_or_description(@search_keyword)
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def section_title(order)
    case order.state
    when "address"
      "お届け先情報"
    when "payment"
      "お支払い方法"
    when "confirm"
      "入力内容確認"
    end
  end
end

app/views/potepan/checkout/_address.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>入力フォーム</h4>
  </div>
</div>
<%= f.fields_for :ship_address do |a| %>
  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :last_name, "性" %>
    <%= a.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :first_name, "名" %>
    <%= a.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :phone, "電話番号" %>
    <%= a.telephone_field :phone, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :zipcode, "郵便番号"%>
    <%= a.text_field :zipcode, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :state, '都道府県' %>
    <%= a.collection_select :state_id, order.ship_address.country.states, :id, :name, {}, { class: "form-control" } %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :city, "市町村" %>
    <%= a.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6 col-xs-12">
    <%= a.label :address1, "番地" %>
    <%= a.text_field :address1, class: "form-control" %>
  </div>
<% end %>

app/views/potepan/checkout/_confirm.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>入力内容確認</h4>
  </div>
</div>
<div class="col-sm-12 col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">お届け先情報</h4>
    </div>
    <div class="panel-body">
      <%= render "shared/confirm_address", address: order.ship_address, order: order %>
    </div>
  </div>
</div>
<div class="col-xs-12">
  <div class="cartListInner">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>商品名</th>
            <th>価格</th>
            <th>数</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "confirm_line_items", collection: order.line_items, as: :line_item %>
        </tbody>
      </table>
    </div>
    <%= render "confirm_amount", order: order %>
  </div>
</div>

app/views/potepan/checkout/_confirm_amount.html.erb
<div class="totalAmountArea">
  <div class="col-sm-4 col-sm-offset-8 col-xs-12">
    <ul class="list-unstyled">
      <li>小計 <span><%= order.display_item_total %></span></li>
      <li>消費税 <span><%= order.display_tax_total %></span></li>
      <li>配送料 <span><%= order.display_ship_total %></span></li>
      <li>総計 <span class="grandTotal"><%= order.display_total %></span></li>
    </ul>
  </div>
</div>

app/views/potepan/checkout/_confirm_line_items.html.erb
<% variant = line_item.variant %>
<tr>
  <td class="col-xs-2">
    <span class="cartImage">
      <%= image_tag(variant.display_image.url(:small)) %>
    </span>
  </td>
  <td class="col-xs-4"><%= link_to line_item.name, potepan_product_path(variant.product.id) %></td>
  <td class="col-xs-2"><%= line_item.display_price %></td>
  <td class="col-xs-2"><%= line_item.quantity %></td>
  <td class="col-xs-2"><%= line_item.display_amount unless line_item.quantity.nil? %></td>
</tr>

app/views/potepan/checkout/_form_hidden.html.erb
<%= f.hidden_field :firstname %>
<%= f.hidden_field :lastname %>
<%= f.hidden_field :company %>
<%= f.hidden_field :address1 %>
<%= f.hidden_field :address2 %>
<%= f.hidden_field :city %>
<%= f.hidden_field :country_id %>
<%= f.hidden_field :state_id %>
<%= f.hidden_field :state_name %>
<%= f.hidden_field :zipcode %>
<%= f.hidden_field :phone %>
<%= f.hidden_field :alternative_phone %>

app/views/potepan/checkout/_gateway.html.erb
<% param_prefix = "payment_source[#{payment_method.id}]" %>
<div class="form-group col-sm-6 col-xs-12">
  <%= label_tag "card_number", "カード番号" %>
  <%= text_field_tag "#{param_prefix}[number]", '4222222222222', { class: 'form-control' } %>
</div>
<div class="form-group col-sm-6 col-xs-12">
  <%= label_tag "name_on_card_#{payment_method.id}", "カード名義人" %>
  <%= text_field_tag "#{param_prefix}[name]", '', { class: "form-control" } %>
</div>
<div class="form-group col-sm-6 col-xs-12">
  <%= label_tag "card_expiry", "有効期限" %>
  <div class="row">
    <div class="col-xs-6">
      <span class="step-drop">
        <%= select_tag "#{param_prefix}[month]", options_for_select(1..12), class: "select-drop" %>
      </span>
    </div>
    <div class="col-xs-6">
      <span class="step-drop">
        <%= select_tag "#{param_prefix}[year]", options_for_select([*(Time.current.year)..(Time.current.year + 9)]), class: "select-drop" %>
      </span>
    </div>
  </div>
</div>
<div class="form-group col-sm-6 col-xs-12">
  <%= label_tag "card_code", "セキュリティコード" %>
  <%= password_field_tag "#{param_prefix}[verification_value]", '', class: "form-control" %>
</div>
<% if order.bill_address %>
  <%= fields_for "#{param_prefix}[address_attributes]", order.bill_address do |f| %>
    <%= render 'form_hidden', f: f %>
  <% end %>
<% end %>
<%= hidden_field_tag "#{param_prefix}[cc_type]", '', id: "cc_type" %>

app/views/potepan/checkout/_payment.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>お支払い方法</h4>
  </div>
</div>
<% credit_card = order.payment_by("Credit Card") %>
<%= hidden_field_tag "order[payments_attributes][][payment_method_id]", credit_card.id %>
<%= render credit_card.partial_name, order: order, payment_method: credit_card %>

app/views/potepan/checkout/_steps_page.html.erb
<div class="row progress-wizard" style="border-bottom:0;">
  <div class="col-xs-4 progress-wizard-step complete <%= "fullBar" unless order.address? %>">
    <div class="text-center progress-wizard-stepnum">お届け先情報</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>

  <div class="col-xs-4 progress-wizard-step <%= order.step_design %>">
    <div class="text-center progress-wizard-stepnum">お支払い方法</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>

  <div class="col-xs-4 progress-wizard-step <%= order.confirm? ? "active" : "disabled" %>">
    <div class="text-center progress-wizard-stepnum">入力内容確認</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>
</div>

app/views/potepan/checkout/_submit_form.html.erb
<div class="col-xs-12">
  <div class="well well-lg clearfix">
    <ul class="pager">
      <li class="previous">
        <% if order.address? %>
          <%= link_to "戻る", potepan_cart_path %>
        <% else %>
          <%= link_to "戻る", potepan_checkout_state_path(order.previous_state) %>
        <% end %>
      </li>
      <li class="next">
        <%= f.submit order.confirm? ? "購入確定" : "次へ", class: "next-btn" %>
      </li>
    </ul>
  </div>

app/views/potepan/checkout/edit.html.erb
<% provide :title, "Checkout" %>
<%= render "shared/error_messages", object: @order %>
<%= render "shared/light_section", page_title: section_title(@order) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <%= render 'steps_page', order: @order %>
          <%= form_with model: @order, url: potepan_update_checkout_path(@order.state), local: true do |f| %>
            <%= render @order.state, order: @order, f: f %>
            <%= render 'submit_form', order: @order, f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>