config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root  'home_pages#index'

    get   :cart,     to: "orders#edit"
    patch :cart,     to: "orders#update"
    post  :populate, to: "orders#populate"

    patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout
    get   "/checkout/:state",        to: "checkout#edit",   as: :checkout_state
    get   "/checkout",               to: "checkout#edit"

    resources :orders,              only: [:show, :edit, :update]
    resources :line_items,          only: [:destroy]
    resources :home_pages,          only: [:index]
    resources :categories,          only: [:show]
    resources :products,            only: [:show] do
      collection do
        get :search
      end
    end

    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_message.html.erb
<div class= "flash_messages">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <%= render 'layouts/topbar' %>
  <%= render 'layouts/navbar' %>
</div>

app/views/layouts/_navbar.html.erb
<!-- NAVBAR -->
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("img/logo.png", :alt => "logo"), potepan_root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <%= link_to 'Home', potepan_root_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_search_box.html.erb
<li class="dropdown searchBox">
  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
  <ul class="dropdown-menu dropdown-menu-right">
    <li>
      <%= form_with url: search_potepan_products_path, id: "form01", method: :get, local: true do |f| %>
        <span class="input-group">
          <%= f.text_field :search, class: "form-control", placeholder: "Search…", "aria-describedby" => "basic-addon2", id: "" %>
          <button><span onclick="form01.submit();" class="input-group-addon addPointer" id="basic-addon2">検索</span></button>
        </span>
      <% end %>
    </li>
  </ul>
</li>

app/views/layouts/_topbar.html.erb
<!-- TOPBAR -->
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs"></div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li><span><a href='/login'>ログイン</a><small>or</small><a href='/signup'>新規登録</a></span></li>
            <%= render 'layouts/search_box' %>
          <li class="dropdown">
            <%= link_to potepan_cart_path, class: "dropdown-toggle", "data-toggle" => "dropdown disabled" do %>
              <i class="fa fa-shopping-cart"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <%= csrf_meta_tags %>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>

    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->

    <%= render  'shared/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>